removing GA related scripts
h5bp/html5boilerplate.com pull request #302
Opened 2022-09-17 02:13 UTC by roblarsen

closes #279

2022-09-17 04:07 UTC, coliff commented
We aren’t using that Twitter script either, I think the entire file can be removed.

2022-09-18 04:15 UTC, coliff requested changes
I think we need to run build script to remove it from the docs (dist)

2022-09-19 01:44 UTC, roblarsen commented
I ran the build 👍

2022-09-19 04:01 UTC, coliff approved these changes

2022-09-19 04:01 UTC, merged